[package]
name = "gkr"
version.workspace = true
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ff.workspace = true
ark-std.workspace = true
goldilocks.workspace = true

simple-frontend = { path = "../simple-frontend" }
transcript = { path = "../transcript" }
sumcheck = { path = "../sumcheck" }
multilinear_extensions = { path = "../multilinear_extensions" }
itertools = "0.12.0"
serde.workspace = true
serde_json = "1.0.108"

[dev-dependencies]
tiny-keccak = { version = "2.0.2", features = ["keccak"] }
