[package]
name = "gkr"
version.workspace = true
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ff.workspace = true
ark-std.workspace = true
goldilocks.workspace = true

simple-frontend = { path = "../simple-frontend" }
transcript = { path = "../transcript" }
sumcheck = { path = "../sumcheck" }
multilinear_extensions = { path = "../multilinear_extensions" }
itertools = "0.12.0"
serde.workspace = true
serde_json = "1.0.108"
rayon.workspace = true

[features]
debug_wenqing = []

[[bin]]
name = "counter_in"
path = "examples/counter_in.rs"

[[bin]]
name = "wire_in_with_pad"
path = "examples/wire_in_with_pad.rs"

[[bin]]
name = "fake_hash_lookup_par"
path = "examples/fake_hash_lookup_par.rs"
[dev-dependencies]
tiny-keccak = { version = "2.0.2", features = ["keccak"] }
