version: 2
updates:
  - package-ecosystem: "cargo"
    directories: ["/", "/examples"]
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "riscv-testdata/create_testdata"
    schedule:
      interval: "weekly"
