[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.tests]
args = [
  "test",
  # Run everything but 'benches'.
  "--lib",
  "--bins",
  "--tests",
  "--examples",
  "--workspace",
]
command = "cargo"
workspace = false

[tasks.fmt-all-check]
args = ["fmt", "--all", "--", "--check"]
command = "cargo"
workspace = false

[tasks.fmt-all]
args = ["fmt", "--all"]
command = "cargo"
workspace = false

[tasks.clippy-all]
args = ["clippy", "--all-features", "--all-targets", "--", "-D", "warnings"]
command = "cargo"
workspace = false

[tasks.fmt]
args = ["fmt", "-p", "ceno_zkvm", "--", "--check"]
command = "cargo"
workspace = false

[tasks.riscv_stats]
args = ["run", "--bin", "riscv_stats"]
command = "cargo"
workspace = false

[tasks.clippy]
args = [
  "clippy",
  "--workspace",
  "--all-targets",
  "--",
  "-D",
  "warnings",
]
command = "cargo"
workspace = false
