[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
CORE = { script = ["grep ^cpu\\scores /proc/cpuinfo | uniq |  awk '{print $4}'"] }
RAYON_NUM_THREADS = "${CORE}"
CUR_TARGET = { script = [
        # Command to check if the variable is not set, then assign output of the bash command
        '''
        if [ -z "${TARGET}" ]; then
            TARGET=$(rustc -vV | grep "host" | awk '{print $2}')
            echo "${TARGET}"
        else
            echo "${TARGET}"
        fi
        '''
]}

[tasks.tests]
command = "cargo"
args = ["test", "--lib", "--release", "--target", "${CUR_TARGET}", "--workspace", "--exclude", "singer-pro", "--exclude", "ceno_rt"]

[tasks.fmt-check]
command = "cargo"
args = ["fmt", "--all", "--", "--check"]

[tasks.fmt-all]
command = "cargo"
args = ["fmt", "--all"]

[tasks.clippy-all]
command = "cargo"
args = ["clippy", "--all-features", "--all-targets", "--", "-D", "warnings"]

[tasks.fmt]
command = "cargo"
args = ["fmt", "-p", "ceno_zkvm", "--", "--check"]

[tasks.clippy]
command = "cargo"
args = ["clippy", "-p", "ceno_zkvm", "-p", "mpcs", "-p", "ceno_emul", "-p", "ceno_rt", "--target", "${CUR_TARGET}", "--", "-D", "warnings"]
