[package]
categories.workspace = true
description = "cargo-ceno cli tools"
edition.workspace = true
keywords.workspace = true
license.workspace = true
name = "cargo-ceno"
repository.workspace = true
version.workspace = true

[dependencies]
