[package]
categories.workspace = true
description = "Ceno SDK"
edition.workspace = true
keywords.workspace = true
license.workspace = true
name = "ceno-sdk"
readme.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
