[package]
categories.workspace = true
description = "Multilinear extensions for the Ceno project"
edition.workspace = true
keywords.workspace = true
license.workspace = true
name = "multilinear-extensions"
readme.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
ark-std.workspace = true
ff-ext.workspace = true
itertools.workspace = true
p3.workspace = true
rayon.workspace = true
serde.workspace = true
tracing.workspace = true

[dev-dependencies]
env_logger = "0.11"
log = "0.4"

[features]
default = ["parallel"]
parallel = []
