[package]
categories.workspace = true
description = "Witness for Ceno"
edition.workspace = true
keywords.workspace = true
license.workspace = true
name = "witness"
readme.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
multilinear-extensions.workspace = true

ff-ext.workspace = true
p3.workspace = true
rayon.workspace = true
serde.workspace = true

rand.workspace = true
