[package]
categories.workspace = true
description = "Support for the host port of a Ceno application"
edition.workspace = true
keywords.workspace = true
license.workspace = true
name = "ceno-host"
readme.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
ceno-emul.workspace = true
itertools.workspace = true
rkyv.workspace = true
substrate-bn.workspace = true
tiny-keccak.workspace = true

[dev-dependencies]
ceno-examples.workspace = true
rand.workspace = true
