[package]
categories = ["cryptography", "zk", "blockchain", "ceno"]
description = "Ceno zkVM Keccak Guest Library"
edition = "2021"
keywords = ["cryptography", "zk", "blockchain", "ceno"]
license = "MIT OR Apache-2.0"
name = "ceno_keccak"
readme = "README.md"
repository = "https://github.com/scroll-tech/ceno"
version = "0.1.0"

[dependencies]
ceno_rt = { path = "../../ceno_rt" }
tiny-keccak = { workspace = true }
