[package]
authors = ["debris <marek.kotewicz@gmail.com>", "Scroll Tech"]
categories = ["cryptography", "zk", "blockchain", "ceno"]
description = "Ceno runtime library"
edition = "2021"
keywords = ["cryptography", "zk", "blockchain", "ceno"]
license = "MIT OR Apache-2.0"
name = "ceno_keccak"
readme = "README.md"
repository = "https://github.com/scroll-tech/ceno"
version = "0.1.0"

[dependencies]
tiny-keccak = { workspace = true }
cfg-if = "1.0"
ceno_rt = { path = "../../ceno_rt" }

[[test]]
name = "keccak"
