name: Benchmarks

on:
  push:
    branches:
      - master

jobs:
  benches:
    name: Run Benchmarks
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@master
        with:
          targets: riscv32im-unknown-none-elf
          # TODO(Matthias): see whether we can keep this in sync with rust-toolchain.toml automatically?
          toolchain: nightly-2024-10-03

      - name: Cargo cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            examples/target/
          key: bench-${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: run benchmarks
        run: time cargo bench --workspace --exclude ceno_rt
