name: Reth Regression Benchmark

on:
  pull_request_target:
    types: [labeled]

permissions:
  contents: read
  pull-requests: read

jobs:
  dispatch:
    if: |
      github.event.pull_request.draft == false &&
      github.event.pull_request.head.repo.full_name == github.repository &&
      contains(github.event.pull_request.labels.*.name, 'regression-e2e-reth')
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch benchmark workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          token: ${{ secrets.CENO_RETH_BENCHMARK_DISPATCH_TOKEN }}
          repo: scroll-tech/ceno-reth-benchmark
          workflow: run-benchmark-v2.yml
          ref: ceno
          inputs: |
            {
              "ceno_version": "${{ github.event.pull_request.head.sha }}",
              "source_repository": "${{ github.repository }}",
              "source_pr_number": "${{ github.event.pull_request.number }}",
              "block_number": "23817600",
              "rerun_keygen": "false",
              "recompile_reth": "false",
              "cleanup": "true",
              "ignore_failed": "false"
            }
